[package]
name = "vss-mapping"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128" 
serde = { version = "1.0", features = ["derive"] }
clap = {version = "4.1", features = ["derive"]}